# Generated by Django 4.1 on 2022-10-01 19:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppMercado', '0003_electrodomesticos_marca_muebles_material_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='electrodomesticos',
            name='fecha_publicacion',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='muebles',
            name='fecha_publicacion',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='vehiculos',
            name='fecha_publicacion',
            field=models.CharField(max_length=50),
        ),
    ]
