# Generated by Django 4.1 on 2022-10-01 19:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('AppMercado', '0004_alter_electrodomesticos_fecha_publicacion_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='electrodomesticos',
            name='fecha_publicacion',
        ),
        migrations.RemoveField(
            model_name='muebles',
            name='fecha_publicacion',
        ),
        migrations.RemoveField(
            model_name='vehiculos',
            name='fecha_publicacion',
        ),
    ]
