# Generated by Django 4.1.1 on 2022-09-29 22:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Blog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("titulo", models.CharField(max_length=200)),
                ("cuerpo", models.TextField()),
                ("fecha_publicacion", models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
