# Generated by Django 4.1 on 2022-10-10 22:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_alter_blog_cuerpo'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='subtitulo',
            field=models.CharField(default='texto', max_length=200),
            preserve_default=False,
        ),
    ]
